### ISSUE TITLE
Better info + error handling

### ISSUE THREAD

**Issue by marineks** [smaugdela/42-ft_transcendance#31]
### Todo marine:

- [x] remplacer les users/id par des users/me pour get les infos d'une personne loggé (aka plus de id hardcodé!)
- [x] gérer de façon plus gracieuse les erreurs catched dans le back (= file too large, type de fichier accepté, nickname déjà pris)
- [x] gérer le warning de unsafe origin quand on post une image sur cloudinary
- [x] bien rerender le component quand limage est changée
- [x] voir comment resize les images données par un user (à gérer dans front ou back?)
- [x] styler tout ça
