### ISSUE TITLE
Finir user flow pour authent'

### ISSUE THREAD

**Issue by marineks** [smaugdela/42-ft_transcendance#33]
### Todo
- [x] 2FA component à coder côté front (slider pour l'activer, message et logique pour envoi de mail avec code, component pour rentrer ces infos )
- [x] Update la logique du sign in: intervertir les boutons login/sign up (faire la logique du login => si !user, rediriger vers sign up), link les boutons de connect w/ 42 à celle du back
- [x] transformer le login en image du user avec possibilité de logout en dessous !
- [x] faire le point vert du isActive avec la route /me/check
- [x] reload le chat quand on est loggé
- [x] .env côté front à importer (fait pb car pas reconnu; voir si setup à faire car on a utilisé CRA pour build l'app => pas de quotes ni d'accolades et rajouter `REACT_APP_ `devant chaque var d'environnement)
- [x] gérer les messages d'erreur signup et login
- [x] voir comment redirect sur notre page après successful login 42 (cf. 
> The redirect URI(s). Theses URI(s) are needed if you app acts as a third tier between the 42 data and an user (this flow is called Web Application Flow), and specify where the user need to be redirected after his authentication. If you plan to use your app just as a server-side app, without user interaction, you can set any valid adress, you'll not need theses URI.

=> voir avec simon les URIs qu'on a spécifiées
